snap: Add an 'enabled' config item.
Don't try to run until enabled is set, and automatically run the
migrations when we are enabled

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -22,4 +22,27 @@ then
     exit 1
 fi
 
+base_url="$(snapctl get base-url)"
+enabled="$(snapctl get enabled)"
+
+if [ -n ${enabled} -a \( "${enabled}" != "true" -a "${enabled}" != "false" \) ]
+then
+    echo "Invalid 'enabled' setting: ${enabled}. Valid values are 'true' or 'false'"
+    exit 1
+fi
+
+if [ -n ${base_url} -a \( -z "${enabled}" -o "${enabled}" = "false" \) ]
+then
+    echo "All required configuration available."
+    echo "Plume can now be enabled by setting 'snap set plume enabled=true' and restarting the service \
+with 'snap restart plume'"
+fi
+
+if [ "${enabled}" = "true" -a ! -e ${SNAP_COMMON}/initial-migrations-run ]
+then
+    cd ${SNAP}
+    exec ./set-environment bin/plm migration run --path ${SNAP_DATA}
+    touch ${SNAP_COMMON}/initial-migrations-run
+fi
+
 exit 0
